name: Plugin asset/readme update
on:
  push:
    branches:
      - master
jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: WordPress.org plugin asset/readme update
        run: >
          chmod +x ./.github/workflows/update-readme.yml 
          ./.github/workflows/update-readme.yml
        shell: bash
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}